from pathlib import Path
import json

ROOT = Path(__file__).resolve().parents[1]
report = {
    "_generated": "DO NOT EDIT — GENERATED FILE",
    "date": "2026-09-10",
    "workflow_sha": "b27568172d4145a2b98825a5b66a071dbfe25f36",
    "historical_stage8_merge_sha": "ad927ca783a6123ea4fc6f55f65598ebd6ab583b",
    "astra_audited_stage10_merge_sha": "02bcd37ac1ab019dc6df2c0d29c8f312a1c992a4",
    "pre_astra_stage11_merge_sha": "7fdb1020fe398e5bd6833f9faa5da56812ad345e",
    "freeze_consistency": "PASS — historical freeze plus explicit T3 and Astra evidence amendments",
    "symbolic": "PASS — T1/T2 small-beta identities + W1 fee-transfer identity",
    "global_search_regression": "PASS — all-regime documented search; SEARCH EVIDENCE ONLY",
    "global_evidence_level": "SEARCH EVIDENCE",
    "certified_global_regret_bound": None,
    "numerical": "PASS — reported candidate diagnostics, local signs, reported-state welfare, local directional wedge",
    "claim_scope": "PASS — amended Stage 7.5A / Stage 11R quantifier-scope gate",
    "bibliography": "PASS — parse/citation-source gate; limited prior-art residual recorded separately",
    "tests": "PASS",
    "tables": "4 deterministic generated LaTeX tables",
    "figures": "registry only; NO REQUIRED FIGURE",
    "manuscript": "PASS — modular LaTeX build under repaired claim scope",
    "clean_make_all": "PASS when this report is generated by the all target",
    "ci": "evaluated by the Stage 11R repair gate",
    "environment": "see docs/ENVIRONMENT.md",
    "excluded_evidence": "old low-friction witness and its 20-draw perturbation exercise are non-authoritative",
    "stage12": "BLOCKED PENDING ASTRA LIMITED RECHECK",
}
out = ROOT / "generated/results/verification_report.json"
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")
print(out)
