from pathlib import Path
import json

ROOT = Path(__file__).resolve().parents[1]
report = {
    "_generated": "DO NOT EDIT — GENERATED FILE",
    "date": "2026-09-10",
    "workflow_sha": "b27568172d4145a2b98825a5b66a071dbfe25f36",
    "stage9_template_sha": "b22be041db59283ae9feb70b122c9eb73969c898",
    "stage8_merge_sha": "ad927ca783a6123ea4fc6f55f65598ebd6ab583b",
    "stage75a_certified_input_sha": "eeb48a3dd76ab6f43d5de175b12c3f374746db0f",
    "freeze_consistency": "PASS",
    "symbolic": "PASS — small-beta identities + fee-transfer identity",
    "global_equilibrium_regression": "PASS — independent all-regime repaired audit",
    "numerical": "PASS — repaired witness/signs/welfare/local wedge",
    "claim_scope": "PASS — Stage 7.5A quantifier/scope gate",
    "bibliography": "PASS — parse/citation-source gate",
    "tests": "PASS",
    "tables": "4 deterministic generated LaTeX tables",
    "figures": "registry only; no frozen Stage-8 result requires a production figure",
    "manuscript": "PASS — modular LaTeX build under current frozen theory",
    "clean_make_all": "PASS when this report is generated by the all target",
    "ci": "evaluated on Stage-9 PR HEAD",
    "environment": "see docs/ENVIRONMENT.md",
    "excluded_evidence": "old low-friction witness and its 20-draw perturbation exercise are non-authoritative",
}
out = ROOT / "generated/results/verification_report.json"
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")
print(out)
